services:
  - type: static
    name: jsu-drink-tracker
    env: static
    branch: main
    buildCommand: .render/build.sh
    staticPublishPath: dist
    rootDir: JSU Drink Tracker
    buildFilter:
      paths:
        - JSU Drink Tracker/**
